name: update release
on:
  workflow_dispatch:
  schedule:
    - cron: 30 0 * * *
jobs:
  update-release:
    name: update release
    runs-on: ubuntu-latest
    steps:
      - name: Set safe directory # https://github.com/actions/checkout/issues/760
        run: |
          set -x
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git config --global --add safe.directory /github/workspace

      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run update script
        run: |
          python -m pip install -r requirements.txt
          python update.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
