name: update release
on:
  workflow_dispatch:
  schedule:
    - cron: 30 00 */3 * *
jobs:
  update-release:
    name: update release
    runs-on: ubuntu-latest
    steps:
      - name: Set safe directory # https://github.com/actions/checkout/issues/760
        run: |
          set -x
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git config --global --add safe.directory /github/workspace

      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run update script
        run: |
          # https://stackoverflow.com/questions/59282476/error-rpc-failed-curl-92-http-2-stream-0-was-not-closed-cleanly-protocol-erro
          git config --global http.version HTTP/1.1
          git config --global user.name 'Kien Nguyen'
          git config --global user.email 'kiennt2609@gmail.com'
          python -m pip install -r requirements.txt
          python update.py
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_USERNAME: 'ntk148v'
          FORCE_UPDATE: 'false'
        shell: bash
